-- MySQL Script generated by MySQL Workbench
-- Thu Sep 14 15:04:07 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`promo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`promo` (
                                              id INT PRIMARY KEY AUTO_INCREMENT,
                                              name VARCHAR(255) NOT NULL);

INSERT INTO `mydb`.`promo` (name) VALUES ('Promo Janvier 2023');
INSERT INTO `mydb`.`promo` (name) VALUES ('Promo Decembre 2022');
INSERT INTO `mydb`.`promo` (name) VALUES ('Promo Mai 2021');

-- -----------------------------------------------------
-- Table `mydb`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`member` (
                                               id INT PRIMARY KEY AUTO_INCREMENT,
                                               name VARCHAR(16) NOT NULL,
                                               email VARCHAR(255) NULL,
                                               birthdate DATETIME NOT NULL,
                                               `promo_id` INT NOT NULL,
                                               INDEX `fk_member_promo1_idx` (`promo_id` ASC) VISIBLE,
                                               CONSTRAINT `fk_member_promo1`
                                                   FOREIGN KEY (`promo_id`)
                                                       REFERENCES `mydb`.`promo` (`id`)
                                                       ON DELETE NO ACTION
                                                       ON UPDATE NO ACTION);

INSERT INTO `mydb`.`member` (name, email, birthdate, promo_id ) VALUES ('Juliette','juliette@taki','2000-12-23',1);
INSERT INTO `mydb`.`member` (name, email, birthdate, promo_id ) VALUES ('Lucas','lucas@taki','2001-10-06',2);
INSERT INTO `mydb`.`member` (name, email, birthdate, promo_id ) VALUES ('Aurelien','aurelien@taki','2003-04-14',2);
INSERT INTO `mydb`.`member` (name, email, birthdate, promo_id ) VALUES ('Paulin','paulin@taki','2001-02-23',3);
INSERT INTO `mydb`.`member` (name, email, birthdate, promo_id ) VALUES ('Lea','lea@taki','2001-06-13',3);

-- -----------------------------------------------------
-- Table `mydb`.`codeReview`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`codeReview` (
                                                   id INT PRIMARY KEY AUTO_INCREMENT,
                                                   name VARCHAR(255) NOT NULL,
                                                   description VARCHAR(45) NULL,
                                                   datetime DATETIME NULL,
                                                   promo_id INT NOT NULL,

                                                   INDEX `fk_codeReview_promo1_idx` (`promo_id` ASC) VISIBLE,
                                                   CONSTRAINT `fk_codeReview_promo1`
                                                       FOREIGN KEY (`promo_id`)
                                                           REFERENCES `mydb`.`promo` (`id`)
                                                           ON DELETE NO ACTION
                                                           ON UPDATE NO ACTION);

INSERT INTO `mydb`.`codeReview` (name, description, datetime, promo_id ) VALUES ('1ere revu projet','definir les besoins du projet','2023-09-13',1);
INSERT INTO `mydb`.`codeReview` (name, description, datetime, promo_id ) VALUES ('WelcomePool','la vie est cool','2023-09-22',2);
INSERT INTO `mydb`.`codeReview` (name, description, datetime, promo_id ) VALUES ('WelcomePool bis','la vie est cool','2023-10-12',3);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
